apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-platform-config
  namespace: restaurant-platform
  labels:
    app: restaurant-platform
    environment: production
    managed-by: terraform
    version: 1.0.0
  annotations:
    description: Production configuration for restaurant platform services
    last-updated: "2024-01-20"
    update-strategy: rolling-restart
data:
  # Application Core Settings
  NODE_ENV: "production"
  PORT: "3000"
  API_VERSION: "v1"
  LOG_LEVEL: "info"
  MAX_PAYLOAD_SIZE: "10mb"
  API_TIMEOUT: "30000"
  METRICS_PATH: "/metrics"

  # Database Configuration
  MONGODB_DATABASE: "restaurant_platform"
  REDIS_HOST: "redis-master.restaurant-platform.svc.cluster.local"
  REDIS_PORT: "6379"
  CACHE_TTL: "3600"

  # External Service Integration
  AWS_REGION: "us-east-1"
  S3_BUCKET: "restaurant-platform-media"
  CDN_URL: "https://cdn.restaurant-platform.com"
  MAPS_API_URL: "https://maps.googleapis.com/maps/api/js"
  STRIPE_API_VERSION: "2023-10-16"

  # Security Settings
  RATE_LIMIT_WINDOW: "60000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  CORS_ALLOWED_ORIGINS: "https://*.restaurant-platform.com"