# Kubernetes Secret API version: v1
apiVersion: v1
kind: Secret
metadata:
  name: restaurant-platform-secrets
  namespace: restaurant-platform
  labels:
    app: restaurant-platform
    environment: production
    managed-by: manual
    component: configuration
type: Opaque
data:
  # Database Credentials
  # Connection strings and credentials for data stores
  MONGODB_URI: ${BASE64_MONGODB_URI}
  POSTGRES_URL: ${BASE64_POSTGRES_URL}
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}

  # Authentication Secrets
  # JWT and authentication service credentials
  JWT_SECRET: ${BASE64_JWT_SECRET}
  JWT_REFRESH_SECRET: ${BASE64_JWT_REFRESH_SECRET}
  SESSION_SECRET: ${BASE64_SESSION_SECRET}
  AUTH0_CLIENT_SECRET: ${BASE64_AUTH0_CLIENT_SECRET}
  AUTH0_API_SECRET: ${BASE64_AUTH0_API_SECRET}

  # External Service API Keys
  # Third-party service integration credentials
  STRIPE_SECRET_KEY: ${BASE64_STRIPE_SECRET_KEY}
  STRIPE_WEBHOOK_SECRET: ${BASE64_STRIPE_WEBHOOK_SECRET}
  MAPS_API_KEY: ${BASE64_MAPS_API_KEY}
  AWS_ACCESS_KEY_ID: ${BASE64_AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${BASE64_AWS_SECRET_ACCESS_KEY}
  SENDGRID_API_KEY: ${BASE64_SENDGRID_API_KEY}
  SENTRY_DSN: ${BASE64_SENTRY_DSN}

  # Encryption Keys
  # Cryptographic keys for data encryption
  CRYPTO_KEY: ${BASE64_CRYPTO_KEY}
  CRYPTO_IV: ${BASE64_CRYPTO_IV}
  CRYPTO_SALT: ${BASE64_CRYPTO_SALT}